apiVersion: v1
kind: Secret
metadata:
  name: commerce-common-secret
  namespace: commerce
  labels:
    app.kubernetes.io/part-of: commerce
type: Opaque
data:
  # Database credentials (base64 encoded)
  # admin
  DB_USERNAME: YWRtaW4=
  # admin1234
  DB_PASSWORD: YWRtaW4xMjM0
  # JWT Secret (base64 encoded)
  # koosco-jwt-secret-key-for-development-environment-2024
  JWT_SECRET: a29vc2NvLWp3dC1zZWNyZXQta2V5LWZvci1kZXZlbG9wbWVudC1lbnZpcm9ubWVudC0yMDI0
